# Numpy

In [1]:
#Numpy
# Numpy stands for numericaal python, its a core scientific computing Library provide multidimensional array

# it also has function to work in domain of linear algebra, matrix etx
# Its open source
# Its was devloped in C programming Language
# we can create array in numpy

In [2]:
import numpy as np
# hetrogeneous
hetro=np.array([11,"yo",True])
print("hetrogeneous :",hetro)
# homogeneous
homo=np.array([1,2,3])
print("homogeneous :",homo)
print(hetro.ndim,homo.ndim)

hetrogeneous : ['11' 'yo' 'True']
homogeneous : [1 2 3]
1 1


# 0d array

In [3]:
import numpy as np
a=np.array(42)
print(a),a.ndim
# 0 dimensional array

42


(None, 0)

# 1d array

In [4]:
import numpy as np
arr=np.array([10,20,30,40,50],np.int32)
print(arr)
print(arr.ndim)
print(arr.shape,"it contains 5 0d array")

[10 20 30 40 50]
1
(5,) it contains 5 0d array


# 2d array


In [5]:
a=[[10,20,30,40,50],
   [10,20,30,40,50],
   [10,20,30,40,50],
   [10,20,30,40,50]]
arr= np.array(a)
print(arr)
print(arr.ndim)
print(arr.shape,"it has 4 1d arrays, 5 0d array")


[[10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]]
2
(4, 5) it has 4 1d arrays, 5 0d array


# 3d array

In [6]:
 a=[[[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50]],
[[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50]],
[[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50]]]

arr= np.array(a)
print(arr)
print(arr.ndim)
print(arr.shape,"it has 3 2d array, 4 1d array, and 5 0d array")

[[[10 20 30 40 50]
  [10 20 30 40 50]
  [10 20 30 40 50]
  [10 20 30 40 50]]

 [[10 20 30 40 50]
  [10 20 30 40 50]
  [10 20 30 40 50]
  [10 20 30 40 50]]

 [[10 20 30 40 50]
  [10 20 30 40 50]
  [10 20 30 40 50]
  [10 20 30 40 50]]]
3
(3, 4, 5) it has 3 2d array, 4 1d array, and 5 0d array


# 5 mechanism for creating numpy array
conversion from other python structres such as list, tuples etc

In [7]:
listarray=np.array([1,2,3],np.int8) # you can use np.int to select bits
listarray.shape,listarray.dtype,listarray.ndim,listarray.size
# in 1 d we will have only rows so it will be 3 rows

((3,), dtype('int8'), 1, 3)

listarray2=np.array([[0,1,2],[3,4,5]],np.int8)
print(listarray2)
print(listarray2[0,2])
listarray2.shape,listarray2.dtype,listarray2.ndim,listarray2.size

# Creating arrray of zeros

In [8]:
zeroarray=np.zeros((3,3))
print(zeroarray)
# this will create a array of 3 X 3 with zeros as it's elements
zeroarray.shape,zeroarray.ndim

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


((3, 3), 2)

# creating array with arange

In [9]:
rangearray=np.arange(5)
print(rangearray)
print(rangearray.shape)
print(rangearray.ndim)


[0 1 2 3 4]
(5,)
1


# linspace array

In [10]:
linarray=np.linspace(1,2,4) # it will give me 4 elements with equal linear space between 1 and 2
print(linarray)

[1.         1.33333333 1.66666667 2.        ]


In [11]:
# let me show you anothert example
linarray2=np.linspace(1,5,10)
print(linarray2)
print(linarray2.shape)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
(10,)


# empty array- create array of random no's

In [12]:
emparray=np.empty((2,2))
print(emparray)

[[1.         1.33333333]
 [1.66666667 2.        ]]


# empty_like array- creates the same size of array u give with random no's

In [13]:
emplikearray=np.empty_like(listarray) # i pastly created list array which i used in this function.
print(emplikearray)# this function copied the size and shape of the list array and created a new array with random no's

[120   0 -90]


# Identity array

In [14]:
idarray=np.identity(3) # this gave yje identity array of 3X3
print(idarray)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# reshaping array

In [15]:
array3=np.arange(9)
print(array3)
print(array3.ndim)
array4=array3.reshape(3,3)
print(array4)
print(array4.ndim)
array5=array4.ravel()
print(array5)
print(array5.ndim)

[0 1 2 3 4 5 6 7 8]
1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
2
[0 1 2 3 4 5 6 7 8]
1


# Transpose an array

In [16]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print(x.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [17]:
#  xx=x.flat
# for item in xx:
#     print(item)

In [18]:
y=np.array([20,55,444,333])
print(y.argmax()) # give the index value wherebthere is the largest value
print(y.argmin()) # give the index value where the smallest value is available
y.argsort() # sort ntje index values of the array in ascending order

2
0


array([0, 1, 3, 2], dtype=int64)

In [19]:
x1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x1)
print(x1.argmax()) # it will take all elements of an array in a single line and then give the index value of the highest element
print(x1.argmin())
print(x1.argsort())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8
0
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [20]:
# arg functions usiong axis
print(x1)
print(x1.argmax(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 2 2]


# Mathematical functions using numpy

In [21]:
# lets add two matrices
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(a)
print(b)
print(a+b,'addition')
print(a*b,"multiplication")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[ 12  24  36]
 [ 48  60  72]
 [ 84  96 108]] addition
[[ 11  44  99]
 [176 275 396]
 [539 704 891]] multiplication


In [22]:
# taking eelement wise square root in numpy
c=np.square(a)
print(c)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


# find elements

In [23]:
print(a)
print(np.where(a>5))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))


# changing elements in a array

In [24]:
x2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x2)
x2[2][2]=0
print(x2, "changed values")
print(x2.ndim)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 0]] changed values
2
